/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Assertion model module.
 * @module model/Assertion
 * @version 1.0.0
 */
class Assertion {
    /**
     * Constructs a new <code>Assertion</code>.
     * @alias module:model/Assertion
     * @param statusCodeIs400 {Boolean} 
     */
    constructor(statusCodeIs400) { 
        
        Assertion.initialize(this, statusCodeIs400);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, statusCodeIs400) { 
        obj['Status code is 400'] = statusCodeIs400;
    }

    /**
     * Constructs a <code>Assertion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Assertion} obj Optional instance to populate.
     * @return {module:model/Assertion} The populated <code>Assertion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Assertion();

            if (data.hasOwnProperty('Status code is 400')) {
                obj['Status code is 400'] = ApiClient.convertToType(data['Status code is 400'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} Status code is 400
 */
Assertion.prototype['Status code is 400'] = undefined;






export default Assertion;

