/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Assertions model module.
 * @module model/Assertions
 * @version 1.0.0
 */
class Assertions {
    /**
     * Constructs a new <code>Assertions</code>.
     * @alias module:model/Assertions
     * @param total {Number} 
     * @param failed {Number} 
     */
    constructor(total, failed) { 
        
        Assertions.initialize(this, total, failed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, total, failed) { 
        obj['total'] = total;
        obj['failed'] = failed;
    }

    /**
     * Constructs a <code>Assertions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Assertions} obj Optional instance to populate.
     * @return {module:model/Assertions} The populated <code>Assertions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Assertions();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('failed')) {
                obj['failed'] = ApiClient.convertToType(data['failed'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} total
 */
Assertions.prototype['total'] = undefined;

/**
 * @member {Number} failed
 */
Assertions.prototype['failed'] = undefined;






export default Assertions;

