/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Body3 model module.
 * @module model/Body3
 * @version 1.0.0
 */
class Body3 {
    /**
     * Constructs a new <code>Body3</code>.
     * @alias module:model/Body3
     * @param contentLength {Number} 
     * @param mode {String} 
     */
    constructor(contentLength, mode) { 
        
        Body3.initialize(this, contentLength, mode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contentLength, mode) { 
        obj['contentLength'] = contentLength;
        obj['mode'] = mode;
    }

    /**
     * Constructs a <code>Body3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body3} obj Optional instance to populate.
     * @return {module:model/Body3} The populated <code>Body3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body3();

            if (data.hasOwnProperty('contentLength')) {
                obj['contentLength'] = ApiClient.convertToType(data['contentLength'], 'Number');
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} contentLength
 */
Body3.prototype['contentLength'] = undefined;

/**
 * @member {String} mode
 */
Body3.prototype['mode'] = undefined;






export default Body3;

