/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Body model module.
 * @module model/Body
 * @version 1.0.0
 */
class Body {
    /**
     * Constructs a new <code>Body</code>.
     * @alias module:model/Body
     * @param mode {String} 
     * @param formdata {Array.<String>} 
     */
    constructor(mode, formdata) { 
        
        Body.initialize(this, mode, formdata);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mode, formdata) { 
        obj['mode'] = mode;
        obj['formdata'] = formdata;
    }

    /**
     * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body} obj Optional instance to populate.
     * @return {module:model/Body} The populated <code>Body</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body();

            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
            }
            if (data.hasOwnProperty('formdata')) {
                obj['formdata'] = ApiClient.convertToType(data['formdata'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} mode
 */
Body.prototype['mode'] = undefined;

/**
 * @member {Array.<String>} formdata
 */
Body.prototype['formdata'] = undefined;






export default Body;

