/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Info5 from './Info5';
import Item6 from './Item6';
import Variable2 from './Variable2';

/**
 * The Collection13 model module.
 * @module model/Collection13
 * @version 1.0.0
 */
class Collection13 {
    /**
     * Constructs a new <code>Collection13</code>.
     * @alias module:model/Collection13
     * @param info {module:model/Info5} 
     * @param item {Array.<module:model/Item6>} 
     * @param variable {Array.<module:model/Variable2>} 
     */
    constructor(info, item, variable) { 
        
        Collection13.initialize(this, info, item, variable);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, info, item, variable) { 
        obj['info'] = info;
        obj['item'] = item;
        obj['variable'] = variable;
    }

    /**
     * Constructs a <code>Collection13</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Collection13} obj Optional instance to populate.
     * @return {module:model/Collection13} The populated <code>Collection13</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Collection13();

            if (data.hasOwnProperty('info')) {
                obj['info'] = Info5.constructFromObject(data['info']);
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ApiClient.convertToType(data['item'], [Item6]);
            }
            if (data.hasOwnProperty('variable')) {
                obj['variable'] = ApiClient.convertToType(data['variable'], [Variable2]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Info5} info
 */
Collection13.prototype['info'] = undefined;

/**
 * @member {Array.<module:model/Item6>} item
 */
Collection13.prototype['item'] = undefined;

/**
 * @member {Array.<module:model/Variable2>} variable
 */
Collection13.prototype['variable'] = undefined;






export default Collection13;

