/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Schemas from './Schemas';

/**
 * The Components model module.
 * @module model/Components
 * @version 1.0.0
 */
class Components {
    /**
     * Constructs a new <code>Components</code>.
     * @alias module:model/Components
     * @param schemas {module:model/Schemas} 
     */
    constructor(schemas) { 
        
        Components.initialize(this, schemas);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, schemas) { 
        obj['schemas'] = schemas;
    }

    /**
     * Constructs a <code>Components</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Components} obj Optional instance to populate.
     * @return {module:model/Components} The populated <code>Components</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Components();

            if (data.hasOwnProperty('schemas')) {
                obj['schemas'] = Schemas.constructFromObject(data['schemas']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Schemas} schemas
 */
Components.prototype['schemas'] = undefined;






export default Components;

