/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Config model module.
 * @module model/Config
 * @version 1.0.0
 */
class Config {
    /**
     * Constructs a new <code>Config</code>.
     * @alias module:model/Config
     * @param headers {Array.<String>} 
     * @param matchBody {Boolean} 
     * @param matchQueryParams {Boolean} 
     * @param matchWildcards {Boolean} 
     */
    constructor(headers, matchBody, matchQueryParams, matchWildcards) { 
        
        Config.initialize(this, headers, matchBody, matchQueryParams, matchWildcards);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, headers, matchBody, matchQueryParams, matchWildcards) { 
        obj['headers'] = headers;
        obj['matchBody'] = matchBody;
        obj['matchQueryParams'] = matchQueryParams;
        obj['matchWildcards'] = matchWildcards;
    }

    /**
     * Constructs a <code>Config</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Config} obj Optional instance to populate.
     * @return {module:model/Config} The populated <code>Config</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Config();

            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], ['String']);
            }
            if (data.hasOwnProperty('matchBody')) {
                obj['matchBody'] = ApiClient.convertToType(data['matchBody'], 'Boolean');
            }
            if (data.hasOwnProperty('matchQueryParams')) {
                obj['matchQueryParams'] = ApiClient.convertToType(data['matchQueryParams'], 'Boolean');
            }
            if (data.hasOwnProperty('matchWildcards')) {
                obj['matchWildcards'] = ApiClient.convertToType(data['matchWildcards'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} headers
 */
Config.prototype['headers'] = undefined;

/**
 * @member {Boolean} matchBody
 */
Config.prototype['matchBody'] = undefined;

/**
 * @member {Boolean} matchQueryParams
 */
Config.prototype['matchQueryParams'] = undefined;

/**
 * @member {Boolean} matchWildcards
 */
Config.prototype['matchWildcards'] = undefined;






export default Config;

