/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Contracttest1 model module.
 * @module model/Contracttest1
 * @version 1.0.0
 */
class Contracttest1 {
    /**
     * Constructs a new <code>Contracttest1</code>.
     * @alias module:model/Contracttest1
     * @param id {String} 
     * @param name {String} 
     * @param updatedAt {String} 
     * @param collectionId {String} 
     */
    constructor(id, name, updatedAt, collectionId) { 
        
        Contracttest1.initialize(this, id, name, updatedAt, collectionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, updatedAt, collectionId) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['updatedAt'] = updatedAt;
        obj['collectionId'] = collectionId;
    }

    /**
     * Constructs a <code>Contracttest1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Contracttest1} obj Optional instance to populate.
     * @return {module:model/Contracttest1} The populated <code>Contracttest1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Contracttest1();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('collectionId')) {
                obj['collectionId'] = ApiClient.convertToType(data['collectionId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Contracttest1.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Contracttest1.prototype['name'] = undefined;

/**
 * @member {String} updatedAt
 */
Contracttest1.prototype['updatedAt'] = undefined;

/**
 * @member {String} collectionId
 */
Contracttest1.prototype['collectionId'] = undefined;






export default Contracttest1;

