/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationJson from './ApplicationJson';

/**
 * The Content model module.
 * @module model/Content
 * @version 1.0.0
 */
class Content {
    /**
     * Constructs a new <code>Content</code>.
     * @alias module:model/Content
     * @param applicationJson {module:model/ApplicationJson} 
     */
    constructor(applicationJson) { 
        
        Content.initialize(this, applicationJson);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, applicationJson) { 
        obj['application/json'] = applicationJson;
    }

    /**
     * Constructs a <code>Content</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Content} obj Optional instance to populate.
     * @return {module:model/Content} The populated <code>Content</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Content();

            if (data.hasOwnProperty('application/json')) {
                obj['application/json'] = ApplicationJson.constructFromObject(data['application/json']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ApplicationJson} application/json
 */
Content.prototype['application/json'] = undefined;






export default Content;

