/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Collection3 from './Collection3';

/**
 * The CreateCollectioninaWorkspace model module.
 * @module model/CreateCollectioninaWorkspace
 * @version 1.0.0
 */
class CreateCollectioninaWorkspace {
    /**
     * Constructs a new <code>CreateCollectioninaWorkspace</code>.
     * @alias module:model/CreateCollectioninaWorkspace
     * @param collection {module:model/Collection3} 
     */
    constructor(collection) { 
        
        CreateCollectioninaWorkspace.initialize(this, collection);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, collection) { 
        obj['collection'] = collection;
    }

    /**
     * Constructs a <code>CreateCollectioninaWorkspace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCollectioninaWorkspace} obj Optional instance to populate.
     * @return {module:model/CreateCollectioninaWorkspace} The populated <code>CreateCollectioninaWorkspace</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCollectioninaWorkspace();

            if (data.hasOwnProperty('collection')) {
                obj['collection'] = Collection3.constructFromObject(data['collection']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Collection3} collection
 */
CreateCollectioninaWorkspace.prototype['collection'] = undefined;






export default CreateCollectioninaWorkspace;

