/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Relations1 from './Relations1';

/**
 * The CreatecollectionfromschemaRequest model module.
 * @module model/CreatecollectionfromschemaRequest
 * @version 1.0.0
 */
class CreatecollectionfromschemaRequest {
    /**
     * Constructs a new <code>CreatecollectionfromschemaRequest</code>.
     * @alias module:model/CreatecollectionfromschemaRequest
     * @param name {String} 
     * @param relations {Array.<module:model/Relations1>} 
     */
    constructor(name, relations) { 
        
        CreatecollectionfromschemaRequest.initialize(this, name, relations);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, relations) { 
        obj['name'] = name;
        obj['relations'] = relations;
    }

    /**
     * Constructs a <code>CreatecollectionfromschemaRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatecollectionfromschemaRequest} obj Optional instance to populate.
     * @return {module:model/CreatecollectionfromschemaRequest} The populated <code>CreatecollectionfromschemaRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatecollectionfromschemaRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('relations')) {
                obj['relations'] = ApiClient.convertToType(data['relations'], [Relations1]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CreatecollectionfromschemaRequest.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/Relations1>} relations
 */
CreatecollectionfromschemaRequest.prototype['relations'] = undefined;






export default CreatecollectionfromschemaRequest;

