/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Version from './Version';

/**
 * The CreateAPIVersionRequest model module.
 * @module model/CreateAPIVersionRequest
 * @version 1.0.0
 */
class CreateAPIVersionRequest {
    /**
     * Constructs a new <code>CreateAPIVersionRequest</code>.
     * @alias module:model/CreateAPIVersionRequest
     * @param version {module:model/Version} 
     */
    constructor(version) { 
        
        CreateAPIVersionRequest.initialize(this, version);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, version) { 
        obj['version'] = version;
    }

    /**
     * Constructs a <code>CreateAPIVersionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateAPIVersionRequest} obj Optional instance to populate.
     * @return {module:model/CreateAPIVersionRequest} The populated <code>CreateAPIVersionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAPIVersionRequest();

            if (data.hasOwnProperty('version')) {
                obj['version'] = Version.constructFromObject(data['version']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Version} version
 */
CreateAPIVersionRequest.prototype['version'] = undefined;






export default CreateAPIVersionRequest;

