/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Error11 from './Error11';

/**
 * The CronPatternNotAllowed model module.
 * @module model/CronPatternNotAllowed
 * @version 1.0.0
 */
class CronPatternNotAllowed {
    /**
     * Constructs a new <code>CronPatternNotAllowed</code>.
     * @alias module:model/CronPatternNotAllowed
     * @param error {module:model/Error11} 
     */
    constructor(error) { 
        
        CronPatternNotAllowed.initialize(this, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error) { 
        obj['error'] = error;
    }

    /**
     * Constructs a <code>CronPatternNotAllowed</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CronPatternNotAllowed} obj Optional instance to populate.
     * @return {module:model/CronPatternNotAllowed} The populated <code>CronPatternNotAllowed</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CronPatternNotAllowed();

            if (data.hasOwnProperty('error')) {
                obj['error'] = Error11.constructFromObject(data['error']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Error11} error
 */
CronPatternNotAllowed.prototype['error'] = undefined;






export default CronPatternNotAllowed;

