/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Details4 model module.
 * @module model/Details4
 * @version 1.0.0
 */
class Details4 {
    /**
     * Constructs a new <code>Details4</code>.
     * @alias module:model/Details4
     * @param param {String} 
     * @param uid {String} 
     */
    constructor(param, uid) { 
        
        Details4.initialize(this, param, uid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, param, uid) { 
        obj['param'] = param;
        obj['uid'] = uid;
    }

    /**
     * Constructs a <code>Details4</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Details4} obj Optional instance to populate.
     * @return {module:model/Details4} The populated <code>Details4</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Details4();

            if (data.hasOwnProperty('param')) {
                obj['param'] = ApiClient.convertToType(data['param'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} param
 */
Details4.prototype['param'] = undefined;

/**
 * @member {String} uid
 */
Details4.prototype['uid'] = undefined;






export default Details4;

