/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Details3 model module.
 * @module model/Details3
 * @version 1.0.0
 */
class Details3 {
    /**
     * Constructs a new <code>Details3</code>.
     * @alias module:model/Details3
     * @param pattern {String} 
     */
    constructor(pattern) { 
        
        Details3.initialize(this, pattern);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pattern) { 
        obj['pattern'] = pattern;
    }

    /**
     * Constructs a <code>Details3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Details3} obj Optional instance to populate.
     * @return {module:model/Details3} The populated <code>Details3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Details3();

            if (data.hasOwnProperty('pattern')) {
                obj['pattern'] = ApiClient.convertToType(data['pattern'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} pattern
 */
Details3.prototype['pattern'] = undefined;






export default Details3;

