/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Details model module.
 * @module model/Details
 * @version 1.0.0
 */
class Details {
    /**
     * Constructs a new <code>Details</code>.
     * @alias module:model/Details
     * @param item {String} 
     * @param id {String} 
     */
    constructor(item, id) { 
        
        Details.initialize(this, item, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, item, id) { 
        obj['item'] = item;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Details</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Details} obj Optional instance to populate.
     * @return {module:model/Details} The populated <code>Details</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Details();

            if (data.hasOwnProperty('item')) {
                obj['item'] = ApiClient.convertToType(data['item'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} item
 */
Details.prototype['item'] = undefined;

/**
 * @member {String} id
 */
Details.prototype['id'] = undefined;






export default Details;

