/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Environment6 model module.
 * @module model/Environment6
 * @version 1.0.0
 */
class Environment6 {
    /**
     * Constructs a new <code>Environment6</code>.
     * @alias module:model/Environment6
     * @param id {String} 
     * @param uid {String} 
     */
    constructor(id, uid) { 
        
        Environment6.initialize(this, id, uid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, uid) { 
        obj['id'] = id;
        obj['uid'] = uid;
    }

    /**
     * Constructs a <code>Environment6</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Environment6} obj Optional instance to populate.
     * @return {module:model/Environment6} The populated <code>Environment6</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Environment6();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Environment6.prototype['id'] = undefined;

/**
 * @member {String} uid
 */
Environment6.prototype['uid'] = undefined;






export default Environment6;

