/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Value from './Value';

/**
 * The Environment1 model module.
 * @module model/Environment1
 * @version 1.0.0
 */
class Environment1 {
    /**
     * Constructs a new <code>Environment1</code>.
     * @alias module:model/Environment1
     * @param id {String} 
     * @param name {String} 
     * @param values {Array.<module:model/Value>} 
     */
    constructor(id, name, values) { 
        
        Environment1.initialize(this, id, name, values);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, values) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['values'] = values;
    }

    /**
     * Constructs a <code>Environment1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Environment1} obj Optional instance to populate.
     * @return {module:model/Environment1} The populated <code>Environment1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Environment1();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [Value]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Environment1.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Environment1.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/Value>} values
 */
Environment1.prototype['values'] = undefined;






export default Environment1;

