/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Assertions2 from './Assertions2';
import Item5 from './Item5';
import Request5 from './Request5';
import Response from './Response';

/**
 * The Execution model module.
 * @module model/Execution
 * @version 1.0.0
 */
class Execution {
    /**
     * Constructs a new <code>Execution</code>.
     * @alias module:model/Execution
     * @param id {Number} 
     * @param item {module:model/Item5} 
     * @param request {module:model/Request5} 
     * @param response {module:model/Response} 
     */
    constructor(id, item, request, response) { 
        
        Execution.initialize(this, id, item, request, response);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, item, request, response) { 
        obj['id'] = id;
        obj['item'] = item;
        obj['request'] = request;
        obj['response'] = response;
    }

    /**
     * Constructs a <code>Execution</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Execution} obj Optional instance to populate.
     * @return {module:model/Execution} The populated <code>Execution</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Execution();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = Item5.constructFromObject(data['item']);
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = Request5.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('response')) {
                obj['response'] = Response.constructFromObject(data['response']);
            }
            if (data.hasOwnProperty('assertions')) {
                obj['assertions'] = Assertions2.constructFromObject(data['assertions']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Execution.prototype['id'] = undefined;

/**
 * @member {module:model/Item5} item
 */
Execution.prototype['item'] = undefined;

/**
 * @member {module:model/Request5} request
 */
Execution.prototype['request'] = undefined;

/**
 * @member {module:model/Response} response
 */
Execution.prototype['response'] = undefined;

/**
 * @member {module:model/Assertions2} assertions
 */
Execution.prototype['assertions'] = undefined;






export default Execution;

