/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Assertion from './Assertion';

/**
 * The Failure model module.
 * @module model/Failure
 * @version 1.0.0
 */
class Failure {
    /**
     * Constructs a new <code>Failure</code>.
     * @alias module:model/Failure
     * @param executionId {Number} 
     * @param name {String} 
     * @param message {String} 
     * @param assertion {module:model/Assertion} 
     */
    constructor(executionId, name, message, assertion) { 
        
        Failure.initialize(this, executionId, name, message, assertion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, executionId, name, message, assertion) { 
        obj['executionId'] = executionId;
        obj['name'] = name;
        obj['message'] = message;
        obj['assertion'] = assertion;
    }

    /**
     * Constructs a <code>Failure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Failure} obj Optional instance to populate.
     * @return {module:model/Failure} The populated <code>Failure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Failure();

            if (data.hasOwnProperty('executionId')) {
                obj['executionId'] = ApiClient.convertToType(data['executionId'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('assertion')) {
                obj['assertion'] = Assertion.constructFromObject(data['assertion']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} executionId
 */
Failure.prototype['executionId'] = undefined;

/**
 * @member {String} name
 */
Failure.prototype['name'] = undefined;

/**
 * @member {String} message
 */
Failure.prototype['message'] = undefined;

/**
 * @member {module:model/Assertion} assertion
 */
Failure.prototype['assertion'] = undefined;






export default Failure;

