/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Parameter from './Parameter';
import Responses from './Responses';

/**
 * The Get model module.
 * @module model/Get
 * @version 1.0.0
 */
class Get {
    /**
     * Constructs a new <code>Get</code>.
     * @alias module:model/Get
     * @param summary {String} 
     * @param operationId {String} 
     * @param parameters {Array.<module:model/Parameter>} 
     * @param responses {module:model/Responses} 
     */
    constructor(summary, operationId, parameters, responses) { 
        
        Get.initialize(this, summary, operationId, parameters, responses);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, summary, operationId, parameters, responses) { 
        obj['summary'] = summary;
        obj['operationId'] = operationId;
        obj['parameters'] = parameters;
        obj['responses'] = responses;
    }

    /**
     * Constructs a <code>Get</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Get} obj Optional instance to populate.
     * @return {module:model/Get} The populated <code>Get</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Get();

            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('operationId')) {
                obj['operationId'] = ApiClient.convertToType(data['operationId'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [Parameter]);
            }
            if (data.hasOwnProperty('responses')) {
                obj['responses'] = Responses.constructFromObject(data['responses']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} summary
 */
Get.prototype['summary'] = undefined;

/**
 * @member {String} operationId
 */
Get.prototype['operationId'] = undefined;

/**
 * @member {Array.<module:model/Parameter>} parameters
 */
Get.prototype['parameters'] = undefined;

/**
 * @member {module:model/Responses} responses
 */
Get.prototype['responses'] = undefined;






export default Get;

