/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Version5 from './Version5';

/**
 * The GetanAPIversion model module.
 * @module model/GetanAPIversion
 * @version 1.0.0
 */
class GetanAPIversion {
    /**
     * Constructs a new <code>GetanAPIversion</code>.
     * @alias module:model/GetanAPIversion
     * @param version {module:model/Version5} 
     */
    constructor(version) { 
        
        GetanAPIversion.initialize(this, version);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, version) { 
        obj['version'] = version;
    }

    /**
     * Constructs a <code>GetanAPIversion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetanAPIversion} obj Optional instance to populate.
     * @return {module:model/GetanAPIversion} The populated <code>GetanAPIversion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetanAPIversion();

            if (data.hasOwnProperty('version')) {
                obj['version'] = Version5.constructFromObject(data['version']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Version5} version
 */
GetanAPIversion.prototype['version'] = undefined;






export default GetanAPIversion;

