/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Relations3 from './Relations3';

/**
 * The GetlinkedrelationsforanAPIversion model module.
 * @module model/GetlinkedrelationsforanAPIversion
 * @version 1.0.0
 */
class GetlinkedrelationsforanAPIversion {
    /**
     * Constructs a new <code>GetlinkedrelationsforanAPIversion</code>.
     * @alias module:model/GetlinkedrelationsforanAPIversion
     * @param relations {module:model/Relations3} 
     */
    constructor(relations) { 
        
        GetlinkedrelationsforanAPIversion.initialize(this, relations);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, relations) { 
        obj['relations'] = relations;
    }

    /**
     * Constructs a <code>GetlinkedrelationsforanAPIversion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetlinkedrelationsforanAPIversion} obj Optional instance to populate.
     * @return {module:model/GetlinkedrelationsforanAPIversion} The populated <code>GetlinkedrelationsforanAPIversion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetlinkedrelationsforanAPIversion();

            if (data.hasOwnProperty('relations')) {
                obj['relations'] = Relations3.constructFromObject(data['relations']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Relations3} relations
 */
GetlinkedrelationsforanAPIversion.prototype['relations'] = undefined;






export default GetlinkedrelationsforanAPIversion;

