/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Contracttest1 from './Contracttest1';

/**
 * The Getrelationsofatype model module.
 * @module model/Getrelationsofatype
 * @version 1.0.0
 */
class Getrelationsofatype {
    /**
     * Constructs a new <code>Getrelationsofatype</code>.
     * @alias module:model/Getrelationsofatype
     * @param contracttest {Array.<module:model/Contracttest1>} 
     */
    constructor(contracttest) { 
        
        Getrelationsofatype.initialize(this, contracttest);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contracttest) { 
        obj['contracttest'] = contracttest;
    }

    /**
     * Constructs a <code>Getrelationsofatype</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Getrelationsofatype} obj Optional instance to populate.
     * @return {module:model/Getrelationsofatype} The populated <code>Getrelationsofatype</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Getrelationsofatype();

            if (data.hasOwnProperty('contracttest')) {
                obj['contracttest'] = ApiClient.convertToType(data['contracttest'], [Contracttest1]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Contracttest1>} contracttest
 */
Getrelationsofatype.prototype['contracttest'] = undefined;






export default Getrelationsofatype;

