/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Api1 from './Api1';

/**
 * The GetsingleAPI model module.
 * @module model/GetsingleAPI
 * @version 1.0.0
 */
class GetsingleAPI {
    /**
     * Constructs a new <code>GetsingleAPI</code>.
     * @alias module:model/GetsingleAPI
     * @param api {module:model/Api1} 
     */
    constructor(api) { 
        
        GetsingleAPI.initialize(this, api);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, api) { 
        obj['api'] = api;
    }

    /**
     * Constructs a <code>GetsingleAPI</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetsingleAPI} obj Optional instance to populate.
     * @return {module:model/GetsingleAPI} The populated <code>GetsingleAPI</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetsingleAPI();

            if (data.hasOwnProperty('api')) {
                obj['api'] = Api1.constructFromObject(data['api']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Api1} api
 */
GetsingleAPI.prototype['api'] = undefined;






export default GetsingleAPI;

