/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Schema2 from './Schema2';

/**
 * The Getschema model module.
 * @module model/Getschema
 * @version 1.0.0
 */
class Getschema {
    /**
     * Constructs a new <code>Getschema</code>.
     * @alias module:model/Getschema
     * @param schema {module:model/Schema2} 
     */
    constructor(schema) { 
        
        Getschema.initialize(this, schema);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, schema) { 
        obj['schema'] = schema;
    }

    /**
     * Constructs a <code>Getschema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Getschema} obj Optional instance to populate.
     * @return {module:model/Getschema} The populated <code>Getschema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Getschema();

            if (data.hasOwnProperty('schema')) {
                obj['schema'] = Schema2.constructFromObject(data['schema']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Schema2} schema
 */
Getschema.prototype['schema'] = undefined;






export default Getschema;

