/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Input from './Input';

/**
 * The ImportexternalAPIspecificationRequest model module.
 * @module model/ImportexternalAPIspecificationRequest
 * @version 1.0.0
 */
class ImportexternalAPIspecificationRequest {
    /**
     * Constructs a new <code>ImportexternalAPIspecificationRequest</code>.
     * @alias module:model/ImportexternalAPIspecificationRequest
     * @param type {String} 
     * @param input {module:model/Input} 
     */
    constructor(type, input) { 
        
        ImportexternalAPIspecificationRequest.initialize(this, type, input);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, input) { 
        obj['type'] = type;
        obj['input'] = input;
    }

    /**
     * Constructs a <code>ImportexternalAPIspecificationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImportexternalAPIspecificationRequest} obj Optional instance to populate.
     * @return {module:model/ImportexternalAPIspecificationRequest} The populated <code>ImportexternalAPIspecificationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImportexternalAPIspecificationRequest();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('input')) {
                obj['input'] = Input.constructFromObject(data['input']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
ImportexternalAPIspecificationRequest.prototype['type'] = undefined;

/**
 * @member {module:model/Input} input
 */
ImportexternalAPIspecificationRequest.prototype['input'] = undefined;






export default ImportexternalAPIspecificationRequest;

