/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Info3 model module.
 * @module model/Info3
 * @version 1.0.0
 */
class Info3 {
    /**
     * Constructs a new <code>Info3</code>.
     * @alias module:model/Info3
     * @param jobId {String} 
     * @param monitorId {String} 
     * @param name {String} 
     * @param collectionUid {String} 
     * @param status {String} 
     * @param startedAt {String} 
     * @param finishedAt {String} 
     */
    constructor(jobId, monitorId, name, collectionUid, status, startedAt, finishedAt) { 
        
        Info3.initialize(this, jobId, monitorId, name, collectionUid, status, startedAt, finishedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jobId, monitorId, name, collectionUid, status, startedAt, finishedAt) { 
        obj['jobId'] = jobId;
        obj['monitorId'] = monitorId;
        obj['name'] = name;
        obj['collectionUid'] = collectionUid;
        obj['status'] = status;
        obj['startedAt'] = startedAt;
        obj['finishedAt'] = finishedAt;
    }

    /**
     * Constructs a <code>Info3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Info3} obj Optional instance to populate.
     * @return {module:model/Info3} The populated <code>Info3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Info3();

            if (data.hasOwnProperty('jobId')) {
                obj['jobId'] = ApiClient.convertToType(data['jobId'], 'String');
            }
            if (data.hasOwnProperty('monitorId')) {
                obj['monitorId'] = ApiClient.convertToType(data['monitorId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('collectionUid')) {
                obj['collectionUid'] = ApiClient.convertToType(data['collectionUid'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('startedAt')) {
                obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'String');
            }
            if (data.hasOwnProperty('finishedAt')) {
                obj['finishedAt'] = ApiClient.convertToType(data['finishedAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} jobId
 */
Info3.prototype['jobId'] = undefined;

/**
 * @member {String} monitorId
 */
Info3.prototype['monitorId'] = undefined;

/**
 * @member {String} name
 */
Info3.prototype['name'] = undefined;

/**
 * @member {String} collectionUid
 */
Info3.prototype['collectionUid'] = undefined;

/**
 * @member {String} status
 */
Info3.prototype['status'] = undefined;

/**
 * @member {String} startedAt
 */
Info3.prototype['startedAt'] = undefined;

/**
 * @member {String} finishedAt
 */
Info3.prototype['finishedAt'] = undefined;






export default Info3;

