/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Components from './Components';
import Info4 from './Info4';
import Paths from './Paths';
import Server from './Server';

/**
 * The Input model module.
 * @module model/Input
 * @version 1.0.0
 */
class Input {
    /**
     * Constructs a new <code>Input</code>.
     * @alias module:model/Input
     * @param openapi {String} 
     * @param info {module:model/Info4} 
     * @param servers {Array.<module:model/Server>} 
     * @param paths {module:model/Paths} 
     * @param components {module:model/Components} 
     */
    constructor(openapi, info, servers, paths, components) { 
        
        Input.initialize(this, openapi, info, servers, paths, components);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, openapi, info, servers, paths, components) { 
        obj['openapi'] = openapi;
        obj['info'] = info;
        obj['servers'] = servers;
        obj['paths'] = paths;
        obj['components'] = components;
    }

    /**
     * Constructs a <code>Input</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Input} obj Optional instance to populate.
     * @return {module:model/Input} The populated <code>Input</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Input();

            if (data.hasOwnProperty('openapi')) {
                obj['openapi'] = ApiClient.convertToType(data['openapi'], 'String');
            }
            if (data.hasOwnProperty('info')) {
                obj['info'] = Info4.constructFromObject(data['info']);
            }
            if (data.hasOwnProperty('servers')) {
                obj['servers'] = ApiClient.convertToType(data['servers'], [Server]);
            }
            if (data.hasOwnProperty('paths')) {
                obj['paths'] = Paths.constructFromObject(data['paths']);
            }
            if (data.hasOwnProperty('components')) {
                obj['components'] = Components.constructFromObject(data['components']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} openapi
 */
Input.prototype['openapi'] = undefined;

/**
 * @member {module:model/Info4} info
 */
Input.prototype['info'] = undefined;

/**
 * @member {Array.<module:model/Server>} servers
 */
Input.prototype['servers'] = undefined;

/**
 * @member {module:model/Paths} paths
 */
Input.prototype['paths'] = undefined;

/**
 * @member {module:model/Components} components
 */
Input.prototype['components'] = undefined;






export default Input;

