/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import A236b715E682460b97b6C1db24f7612e from './A236b715E682460b97b6C1db24f7612e';
import Model521b0486Ab914d3a918943c9380a0533 from './Model521b0486Ab914d3a918943c9380a0533';

/**
 * The Integrationtest model module.
 * @module model/Integrationtest
 * @version 1.0.0
 */
class Integrationtest {
    /**
     * Constructs a new <code>Integrationtest</code>.
     * @alias module:model/Integrationtest
     * @param _521b0486Ab914d3a918943c9380a0533 {module:model/Model521b0486Ab914d3a918943c9380a0533} 
     * @param a236b715E682460b97b6C1db24f7612e {module:model/A236b715E682460b97b6C1db24f7612e} 
     */
    constructor(_521b0486Ab914d3a918943c9380a0533, a236b715E682460b97b6C1db24f7612e) { 
        
        Integrationtest.initialize(this, _521b0486Ab914d3a918943c9380a0533, a236b715E682460b97b6C1db24f7612e);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _521b0486Ab914d3a918943c9380a0533, a236b715E682460b97b6C1db24f7612e) { 
        obj['521b0486-ab91-4d3a-9189-43c9380a0533'] = _521b0486Ab914d3a918943c9380a0533;
        obj['a236b715-e682-460b-97b6-c1db24f7612e'] = a236b715E682460b97b6C1db24f7612e;
    }

    /**
     * Constructs a <code>Integrationtest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Integrationtest} obj Optional instance to populate.
     * @return {module:model/Integrationtest} The populated <code>Integrationtest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Integrationtest();

            if (data.hasOwnProperty('521b0486-ab91-4d3a-9189-43c9380a0533')) {
                obj['521b0486-ab91-4d3a-9189-43c9380a0533'] = Model521b0486Ab914d3a918943c9380a0533.constructFromObject(data['521b0486-ab91-4d3a-9189-43c9380a0533']);
            }
            if (data.hasOwnProperty('a236b715-e682-460b-97b6-c1db24f7612e')) {
                obj['a236b715-e682-460b-97b6-c1db24f7612e'] = A236b715E682460b97b6C1db24f7612e.constructFromObject(data['a236b715-e682-460b-97b6-c1db24f7612e']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Model521b0486Ab914d3a918943c9380a0533} 521b0486-ab91-4d3a-9189-43c9380a0533
 */
Integrationtest.prototype['521b0486-ab91-4d3a-9189-43c9380a0533'] = undefined;

/**
 * @member {module:model/A236b715E682460b97b6C1db24f7612e} a236b715-e682-460b-97b6-c1db24f7612e
 */
Integrationtest.prototype['a236b715-e682-460b-97b6-c1db24f7612e'] = undefined;






export default Integrationtest;

