/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Event from './Event';
import Request from './Request';

/**
 * The Item model module.
 * @module model/Item
 * @version 1.0.0
 */
class Item {
    /**
     * Constructs a new <code>Item</code>.
     * @alias module:model/Item
     * @param id {String} 
     * @param name {String} 
     * @param event {Array.<module:model/Event>} 
     * @param request {module:model/Request} 
     * @param response {Array.<String>} 
     */
    constructor(id, name, event, request, response) { 
        
        Item.initialize(this, id, name, event, request, response);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, event, request, response) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['event'] = event;
        obj['request'] = request;
        obj['response'] = response;
    }

    /**
     * Constructs a <code>Item</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Item} obj Optional instance to populate.
     * @return {module:model/Item} The populated <code>Item</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Item();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], [Event]);
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = Request.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('response')) {
                obj['response'] = ApiClient.convertToType(data['response'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Item.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Item.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/Event>} event
 */
Item.prototype['event'] = undefined;

/**
 * @member {module:model/Request} request
 */
Item.prototype['request'] = undefined;

/**
 * @member {Array.<String>} response
 */
Item.prototype['response'] = undefined;






export default Item;

