/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Request6 from './Request6';
import Response1 from './Response1';

/**
 * The Item7 model module.
 * @module model/Item7
 * @version 1.0.0
 */
class Item7 {
    /**
     * Constructs a new <code>Item7</code>.
     * @alias module:model/Item7
     * @param name {String} 
     * @param postmanId {String} 
     * @param request {module:model/Request6} 
     * @param response {Array.<module:model/Response1>} 
     */
    constructor(name, postmanId, request, response) { 
        
        Item7.initialize(this, name, postmanId, request, response);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, postmanId, request, response) { 
        obj['name'] = name;
        obj['_postman_id'] = postmanId;
        obj['request'] = request;
        obj['response'] = response;
    }

    /**
     * Constructs a <code>Item7</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Item7} obj Optional instance to populate.
     * @return {module:model/Item7} The populated <code>Item7</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Item7();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('_postman_id')) {
                obj['_postman_id'] = ApiClient.convertToType(data['_postman_id'], 'String');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = Request6.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('response')) {
                obj['response'] = ApiClient.convertToType(data['response'], [Response1]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Item7.prototype['name'] = undefined;

/**
 * @member {String} _postman_id
 */
Item7.prototype['_postman_id'] = undefined;

/**
 * @member {module:model/Request6} request
 */
Item7.prototype['request'] = undefined;

/**
 * @member {Array.<module:model/Response1>} response
 */
Item7.prototype['response'] = undefined;






export default Item7;

