/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Item7 from './Item7';

/**
 * The Item6 model module.
 * @module model/Item6
 * @version 1.0.0
 */
class Item6 {
    /**
     * Constructs a new <code>Item6</code>.
     * @alias module:model/Item6
     * @param name {String} 
     * @param item {Array.<module:model/Item7>} 
     * @param postmanId {String} 
     */
    constructor(name, item, postmanId) { 
        
        Item6.initialize(this, name, item, postmanId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, item, postmanId) { 
        obj['name'] = name;
        obj['item'] = item;
        obj['_postman_id'] = postmanId;
    }

    /**
     * Constructs a <code>Item6</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Item6} obj Optional instance to populate.
     * @return {module:model/Item6} The populated <code>Item6</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Item6();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ApiClient.convertToType(data['item'], [Item7]);
            }
            if (data.hasOwnProperty('_postman_id')) {
                obj['_postman_id'] = ApiClient.convertToType(data['_postman_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Item6.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/Item7>} item
 */
Item6.prototype['item'] = undefined;

/**
 * @member {String} _postman_id
 */
Item6.prototype['_postman_id'] = undefined;






export default Item6;

