/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Item5 model module.
 * @module model/Item5
 * @version 1.0.0
 */
class Item5 {
    /**
     * Constructs a new <code>Item5</code>.
     * @alias module:model/Item5
     * @param id {String} 
     * @param name {String} 
     */
    constructor(id, name) { 
        
        Item5.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Item5</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Item5} obj Optional instance to populate.
     * @return {module:model/Item5} The populated <code>Item5</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Item5();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Item5.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Item5.prototype['name'] = undefined;






export default Item5;

