/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Stats from './Stats';

/**
 * The LastRun model module.
 * @module model/LastRun
 * @version 1.0.0
 */
class LastRun {
    /**
     * Constructs a new <code>LastRun</code>.
     * @alias module:model/LastRun
     * @param status {String} 
     * @param startedAt {String} 
     * @param finishedAt {String} 
     * @param stats {module:model/Stats} 
     */
    constructor(status, startedAt, finishedAt, stats) { 
        
        LastRun.initialize(this, status, startedAt, finishedAt, stats);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, startedAt, finishedAt, stats) { 
        obj['status'] = status;
        obj['startedAt'] = startedAt;
        obj['finishedAt'] = finishedAt;
        obj['stats'] = stats;
    }

    /**
     * Constructs a <code>LastRun</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LastRun} obj Optional instance to populate.
     * @return {module:model/LastRun} The populated <code>LastRun</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LastRun();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('startedAt')) {
                obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'String');
            }
            if (data.hasOwnProperty('finishedAt')) {
                obj['finishedAt'] = ApiClient.convertToType(data['finishedAt'], 'String');
            }
            if (data.hasOwnProperty('stats')) {
                obj['stats'] = Stats.constructFromObject(data['stats']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} status
 */
LastRun.prototype['status'] = undefined;

/**
 * @member {String} startedAt
 */
LastRun.prototype['startedAt'] = undefined;

/**
 * @member {String} finishedAt
 */
LastRun.prototype['finishedAt'] = undefined;

/**
 * @member {module:model/Stats} stats
 */
LastRun.prototype['stats'] = undefined;






export default LastRun;

