/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Mock model module.
 * @module model/Mock
 * @version 1.0.0
 */
class Mock {
    /**
     * Constructs a new <code>Mock</code>.
     * @alias module:model/Mock
     * @param id {String} 
     * @param owner {String} 
     * @param uid {String} 
     * @param collection {String} 
     * @param mockUrl {String} 
     */
    constructor(id, owner, uid, collection, mockUrl) { 
        
        Mock.initialize(this, id, owner, uid, collection, mockUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, owner, uid, collection, mockUrl) { 
        obj['id'] = id;
        obj['owner'] = owner;
        obj['uid'] = uid;
        obj['collection'] = collection;
        obj['mockUrl'] = mockUrl;
    }

    /**
     * Constructs a <code>Mock</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Mock} obj Optional instance to populate.
     * @return {module:model/Mock} The populated <code>Mock</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mock();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
            if (data.hasOwnProperty('mockUrl')) {
                obj['mockUrl'] = ApiClient.convertToType(data['mockUrl'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Mock.prototype['id'] = undefined;

/**
 * @member {String} owner
 */
Mock.prototype['owner'] = undefined;

/**
 * @member {String} uid
 */
Mock.prototype['uid'] = undefined;

/**
 * @member {String} collection
 */
Mock.prototype['collection'] = undefined;

/**
 * @member {String} environment
 */
Mock.prototype['environment'] = undefined;

/**
 * @member {String} mockUrl
 */
Mock.prototype['mockUrl'] = undefined;






export default Mock;

