/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Mock4 model module.
 * @module model/Mock4
 * @version 1.0.0
 */
class Mock4 {
    /**
     * Constructs a new <code>Mock4</code>.
     * @alias module:model/Mock4
     * @param name {String} 
     * @param environment {String} 
     * @param description {String} 
     * @param _private {Boolean} 
     * @param versionTag {String} 
     */
    constructor(name, environment, description, _private, versionTag) { 
        
        Mock4.initialize(this, name, environment, description, _private, versionTag);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, environment, description, _private, versionTag) { 
        obj['name'] = name;
        obj['environment'] = environment;
        obj['description'] = description;
        obj['private'] = _private;
        obj['versionTag'] = versionTag;
    }

    /**
     * Constructs a <code>Mock4</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Mock4} obj Optional instance to populate.
     * @return {module:model/Mock4} The populated <code>Mock4</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mock4();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('private')) {
                obj['private'] = ApiClient.convertToType(data['private'], 'Boolean');
            }
            if (data.hasOwnProperty('versionTag')) {
                obj['versionTag'] = ApiClient.convertToType(data['versionTag'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Mock4.prototype['name'] = undefined;

/**
 * @member {String} environment
 */
Mock4.prototype['environment'] = undefined;

/**
 * @member {String} description
 */
Mock4.prototype['description'] = undefined;

/**
 * @member {Boolean} private
 */
Mock4.prototype['private'] = undefined;

/**
 * @member {String} versionTag
 */
Mock4.prototype['versionTag'] = undefined;






export default Mock4;

