/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Mock2 model module.
 * @module model/Mock2
 * @version 1.0.0
 */
class Mock2 {
    /**
     * Constructs a new <code>Mock2</code>.
     * @alias module:model/Mock2
     * @param collection {String} 
     * @param environment {String} 
     */
    constructor(collection, environment) { 
        
        Mock2.initialize(this, collection, environment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, collection, environment) { 
        obj['collection'] = collection;
        obj['environment'] = environment;
    }

    /**
     * Constructs a <code>Mock2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Mock2} obj Optional instance to populate.
     * @return {module:model/Mock2} The populated <code>Mock2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mock2();

            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} collection
 */
Mock2.prototype['collection'] = undefined;

/**
 * @member {String} environment
 */
Mock2.prototype['environment'] = undefined;






export default Mock2;

