/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Model4ccd755f2c80481bA26249b55e12f5e1 from './Model4ccd755f2c80481bA26249b55e12f5e1';

/**
 * The Mock11 model module.
 * @module model/Mock11
 * @version 1.0.0
 */
class Mock11 {
    /**
     * Constructs a new <code>Mock11</code>.
     * @alias module:model/Mock11
     * @param _4ccd755f2c80481bA26249b55e12f5e1 {module:model/Model4ccd755f2c80481bA26249b55e12f5e1} 
     */
    constructor(_4ccd755f2c80481bA26249b55e12f5e1) { 
        
        Mock11.initialize(this, _4ccd755f2c80481bA26249b55e12f5e1);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _4ccd755f2c80481bA26249b55e12f5e1) { 
        obj['4ccd755f-2c80-481b-a262-49b55e12f5e1'] = _4ccd755f2c80481bA26249b55e12f5e1;
    }

    /**
     * Constructs a <code>Mock11</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Mock11} obj Optional instance to populate.
     * @return {module:model/Mock11} The populated <code>Mock11</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mock11();

            if (data.hasOwnProperty('4ccd755f-2c80-481b-a262-49b55e12f5e1')) {
                obj['4ccd755f-2c80-481b-a262-49b55e12f5e1'] = Model4ccd755f2c80481bA26249b55e12f5e1.constructFromObject(data['4ccd755f-2c80-481b-a262-49b55e12f5e1']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Model4ccd755f2c80481bA26249b55e12f5e1} 4ccd755f-2c80-481b-a262-49b55e12f5e1
 */
Mock11.prototype['4ccd755f-2c80-481b-a262-49b55e12f5e1'] = undefined;






export default Mock11;

