/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Config from './Config';

/**
 * The Mock5 model module.
 * @module model/Mock5
 * @version 1.0.0
 */
class Mock5 {
    /**
     * Constructs a new <code>Mock5</code>.
     * @alias module:model/Mock5
     * @param id {String} 
     * @param owner {String} 
     * @param uid {String} 
     * @param collection {String} 
     * @param mockUrl {String} 
     * @param name {String} 
     * @param config {module:model/Config} 
     * @param environment {String} 
     */
    constructor(id, owner, uid, collection, mockUrl, name, config, environment) { 
        
        Mock5.initialize(this, id, owner, uid, collection, mockUrl, name, config, environment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, owner, uid, collection, mockUrl, name, config, environment) { 
        obj['id'] = id;
        obj['owner'] = owner;
        obj['uid'] = uid;
        obj['collection'] = collection;
        obj['mockUrl'] = mockUrl;
        obj['name'] = name;
        obj['config'] = config;
        obj['environment'] = environment;
    }

    /**
     * Constructs a <code>Mock5</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Mock5} obj Optional instance to populate.
     * @return {module:model/Mock5} The populated <code>Mock5</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mock5();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('mockUrl')) {
                obj['mockUrl'] = ApiClient.convertToType(data['mockUrl'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = Config.constructFromObject(data['config']);
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Mock5.prototype['id'] = undefined;

/**
 * @member {String} owner
 */
Mock5.prototype['owner'] = undefined;

/**
 * @member {String} uid
 */
Mock5.prototype['uid'] = undefined;

/**
 * @member {String} collection
 */
Mock5.prototype['collection'] = undefined;

/**
 * @member {String} mockUrl
 */
Mock5.prototype['mockUrl'] = undefined;

/**
 * @member {String} name
 */
Mock5.prototype['name'] = undefined;

/**
 * @member {module:model/Config} config
 */
Mock5.prototype['config'] = undefined;

/**
 * @member {String} environment
 */
Mock5.prototype['environment'] = undefined;






export default Mock5;

