/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Model4ccd755f2c80481bA26249b55e12f5e1 model module.
 * @module model/Model4ccd755f2c80481bA26249b55e12f5e1
 * @version 1.0.0
 */
class Model4ccd755f2c80481bA26249b55e12f5e1 {
    /**
     * Constructs a new <code>Model4ccd755f2c80481bA26249b55e12f5e1</code>.
     * @alias module:model/Model4ccd755f2c80481bA26249b55e12f5e1
     * @param id {String} 
     * @param name {String} 
     * @param url {String} 
     * @param updatedAt {String} 
     */
    constructor(id, name, url, updatedAt) { 
        
        Model4ccd755f2c80481bA26249b55e12f5e1.initialize(this, id, name, url, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, url, updatedAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['url'] = url;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>Model4ccd755f2c80481bA26249b55e12f5e1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Model4ccd755f2c80481bA26249b55e12f5e1} obj Optional instance to populate.
     * @return {module:model/Model4ccd755f2c80481bA26249b55e12f5e1} The populated <code>Model4ccd755f2c80481bA26249b55e12f5e1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Model4ccd755f2c80481bA26249b55e12f5e1();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Model4ccd755f2c80481bA26249b55e12f5e1.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Model4ccd755f2c80481bA26249b55e12f5e1.prototype['name'] = undefined;

/**
 * @member {String} url
 */
Model4ccd755f2c80481bA26249b55e12f5e1.prototype['url'] = undefined;

/**
 * @member {String} updatedAt
 */
Model4ccd755f2c80481bA26249b55e12f5e1.prototype['updatedAt'] = undefined;






export default Model4ccd755f2c80481bA26249b55e12f5e1;

