/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Model2a9b8fa888b74b8683728e3f6f6e07f2 model module.
 * @module model/Model2a9b8fa888b74b8683728e3f6f6e07f2
 * @version 1.0.0
 */
class Model2a9b8fa888b74b8683728e3f6f6e07f2 {
    /**
     * Constructs a new <code>Model2a9b8fa888b74b8683728e3f6f6e07f2</code>.
     * @alias module:model/Model2a9b8fa888b74b8683728e3f6f6e07f2
     * @param id {String} 
     * @param name {String} 
     * @param updatedAt {String} 
     */
    constructor(id, name, updatedAt) { 
        
        Model2a9b8fa888b74b8683728e3f6f6e07f2.initialize(this, id, name, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, updatedAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>Model2a9b8fa888b74b8683728e3f6f6e07f2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Model2a9b8fa888b74b8683728e3f6f6e07f2} obj Optional instance to populate.
     * @return {module:model/Model2a9b8fa888b74b8683728e3f6f6e07f2} The populated <code>Model2a9b8fa888b74b8683728e3f6f6e07f2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Model2a9b8fa888b74b8683728e3f6f6e07f2();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Model2a9b8fa888b74b8683728e3f6f6e07f2.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Model2a9b8fa888b74b8683728e3f6f6e07f2.prototype['name'] = undefined;

/**
 * @member {String} updatedAt
 */
Model2a9b8fa888b74b8683728e3f6f6e07f2.prototype['updatedAt'] = undefined;






export default Model2a9b8fa888b74b8683728e3f6f6e07f2;

