/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Monitor model module.
 * @module model/Monitor
 * @version 1.0.0
 */
class Monitor {
    /**
     * Constructs a new <code>Monitor</code>.
     * @alias module:model/Monitor
     * @param id {String} 
     * @param name {String} 
     * @param uid {String} 
     * @param owner {String} 
     */
    constructor(id, name, uid, owner) { 
        
        Monitor.initialize(this, id, name, uid, owner);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, uid, owner) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['uid'] = uid;
        obj['owner'] = owner;
    }

    /**
     * Constructs a <code>Monitor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Monitor} obj Optional instance to populate.
     * @return {module:model/Monitor} The populated <code>Monitor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Monitor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Monitor.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Monitor.prototype['name'] = undefined;

/**
 * @member {String} uid
 */
Monitor.prototype['uid'] = undefined;

/**
 * @member {String} owner
 */
Monitor.prototype['owner'] = undefined;






export default Monitor;

