/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Schedule1 from './Schedule1';

/**
 * The Monitor4 model module.
 * @module model/Monitor4
 * @version 1.0.0
 */
class Monitor4 {
    /**
     * Constructs a new <code>Monitor4</code>.
     * @alias module:model/Monitor4
     * @param name {String} 
     * @param schedule {module:model/Schedule1} 
     */
    constructor(name, schedule) { 
        
        Monitor4.initialize(this, name, schedule);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, schedule) { 
        obj['name'] = name;
        obj['schedule'] = schedule;
    }

    /**
     * Constructs a <code>Monitor4</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Monitor4} obj Optional instance to populate.
     * @return {module:model/Monitor4} The populated <code>Monitor4</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Monitor4();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = Schedule1.constructFromObject(data['schedule']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Monitor4.prototype['name'] = undefined;

/**
 * @member {module:model/Schedule1} schedule
 */
Monitor4.prototype['schedule'] = undefined;






export default Monitor4;

