/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Run from './Run';

/**
 * The MonitorRunwithErrors model module.
 * @module model/MonitorRunwithErrors
 * @version 1.0.0
 */
class MonitorRunwithErrors {
    /**
     * Constructs a new <code>MonitorRunwithErrors</code>.
     * @alias module:model/MonitorRunwithErrors
     * @param run {module:model/Run} 
     */
    constructor(run) { 
        
        MonitorRunwithErrors.initialize(this, run);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, run) { 
        obj['run'] = run;
    }

    /**
     * Constructs a <code>MonitorRunwithErrors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MonitorRunwithErrors} obj Optional instance to populate.
     * @return {module:model/MonitorRunwithErrors} The populated <code>MonitorRunwithErrors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MonitorRunwithErrors();

            if (data.hasOwnProperty('run')) {
                obj['run'] = Run.constructFromObject(data['run']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Run} run
 */
MonitorRunwithErrors.prototype['run'] = undefined;






export default MonitorRunwithErrors;

