/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Schedule1 from './Schedule1';

/**
 * The Monitor2 model module.
 * @module model/Monitor2
 * @version 1.0.0
 */
class Monitor2 {
    /**
     * Constructs a new <code>Monitor2</code>.
     * @alias module:model/Monitor2
     * @param name {String} 
     * @param schedule {module:model/Schedule1} 
     * @param collection {String} 
     * @param environment {String} 
     */
    constructor(name, schedule, collection, environment) { 
        
        Monitor2.initialize(this, name, schedule, collection, environment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, schedule, collection, environment) { 
        obj['name'] = name;
        obj['schedule'] = schedule;
        obj['collection'] = collection;
        obj['environment'] = environment;
    }

    /**
     * Constructs a <code>Monitor2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Monitor2} obj Optional instance to populate.
     * @return {module:model/Monitor2} The populated <code>Monitor2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Monitor2();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = Schedule1.constructFromObject(data['schedule']);
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Monitor2.prototype['name'] = undefined;

/**
 * @member {module:model/Schedule1} schedule
 */
Monitor2.prototype['schedule'] = undefined;

/**
 * @member {String} collection
 */
Monitor2.prototype['collection'] = undefined;

/**
 * @member {String} environment
 */
Monitor2.prototype['environment'] = undefined;






export default Monitor2;

