/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Relations1 model module.
 * @module model/Relations1
 * @version 1.0.0
 */
class Relations1 {
    /**
     * Constructs a new <code>Relations1</code>.
     * @alias module:model/Relations1
     * @param type {String} 
     */
    constructor(type) { 
        
        Relations1.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Relations1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Relations1} obj Optional instance to populate.
     * @return {module:model/Relations1} The populated <code>Relations1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Relations1();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
Relations1.prototype['type'] = undefined;






export default Relations1;

