/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Relations model module.
 * @module model/Relations
 * @version 1.0.0
 */
class Relations {
    /**
     * Constructs a new <code>Relations</code>.
     * @alias module:model/Relations
     * @param monitor {Boolean} 
     * @param mock {Boolean} 
     * @param documentation {Boolean} 
     */
    constructor(monitor, mock, documentation) { 
        
        Relations.initialize(this, monitor, mock, documentation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, monitor, mock, documentation) { 
        obj['monitor'] = monitor;
        obj['mock'] = mock;
        obj['documentation'] = documentation;
    }

    /**
     * Constructs a <code>Relations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Relations} obj Optional instance to populate.
     * @return {module:model/Relations} The populated <code>Relations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Relations();

            if (data.hasOwnProperty('monitor')) {
                obj['monitor'] = ApiClient.convertToType(data['monitor'], 'Boolean');
            }
            if (data.hasOwnProperty('mock')) {
                obj['mock'] = ApiClient.convertToType(data['mock'], 'Boolean');
            }
            if (data.hasOwnProperty('documentation')) {
                obj['documentation'] = ApiClient.convertToType(data['documentation'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} monitor
 */
Relations.prototype['monitor'] = undefined;

/**
 * @member {Boolean} mock
 */
Relations.prototype['mock'] = undefined;

/**
 * @member {Boolean} documentation
 */
Relations.prototype['documentation'] = undefined;






export default Relations;

