/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Body from './Body';
import Header from './Header';

/**
 * The Request model module.
 * @module model/Request
 * @version 1.0.0
 */
class Request {
    /**
     * Constructs a new <code>Request</code>.
     * @alias module:model/Request
     * @param url {String} 
     * @param method {String} 
     * @param header {Array.<module:model/Header>} 
     * @param body {module:model/Body} 
     * @param description {String} 
     */
    constructor(url, method, header, body, description) { 
        
        Request.initialize(this, url, method, header, body, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, method, header, body, description) { 
        obj['url'] = url;
        obj['method'] = method;
        obj['header'] = header;
        obj['body'] = body;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>Request</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Request} obj Optional instance to populate.
     * @return {module:model/Request} The populated <code>Request</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Request();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = ApiClient.convertToType(data['header'], [Header]);
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = Body.constructFromObject(data['body']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} url
 */
Request.prototype['url'] = undefined;

/**
 * @member {String} method
 */
Request.prototype['method'] = undefined;

/**
 * @member {Array.<module:model/Header>} header
 */
Request.prototype['header'] = undefined;

/**
 * @member {module:model/Body} body
 */
Request.prototype['body'] = undefined;

/**
 * @member {String} description
 */
Request.prototype['description'] = undefined;






export default Request;

