/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Body3 from './Body3';
import Headers from './Headers';

/**
 * The Request5 model module.
 * @module model/Request5
 * @version 1.0.0
 */
class Request5 {
    /**
     * Constructs a new <code>Request5</code>.
     * @alias module:model/Request5
     * @param method {String} 
     * @param url {String} 
     * @param headers {module:model/Headers} 
     * @param body {module:model/Body3} 
     * @param timestamp {String} 
     */
    constructor(method, url, headers, body, timestamp) { 
        
        Request5.initialize(this, method, url, headers, body, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, method, url, headers, body, timestamp) { 
        obj['method'] = method;
        obj['url'] = url;
        obj['headers'] = headers;
        obj['body'] = body;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>Request5</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Request5} obj Optional instance to populate.
     * @return {module:model/Request5} The populated <code>Request5</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Request5();

            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = Headers.constructFromObject(data['headers']);
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = Body3.constructFromObject(data['body']);
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} method
 */
Request5.prototype['method'] = undefined;

/**
 * @member {String} url
 */
Request5.prototype['url'] = undefined;

/**
 * @member {module:model/Headers} headers
 */
Request5.prototype['headers'] = undefined;

/**
 * @member {module:model/Body3} body
 */
Request5.prototype['body'] = undefined;

/**
 * @member {String} timestamp
 */
Request5.prototype['timestamp'] = undefined;






export default Request5;

