/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Error21 from './Error21';

/**
 * The Schemas model module.
 * @module model/Schemas
 * @version 1.0.0
 */
class Schemas {
    /**
     * Constructs a new <code>Schemas</code>.
     * @alias module:model/Schemas
     * @param error {module:model/Error21} 
     */
    constructor(error) { 
        
        Schemas.initialize(this, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error) { 
        obj['Error'] = error;
    }

    /**
     * Constructs a <code>Schemas</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Schemas} obj Optional instance to populate.
     * @return {module:model/Schemas} The populated <code>Schemas</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Schemas();

            if (data.hasOwnProperty('Error')) {
                obj['Error'] = Error21.constructFromObject(data['Error']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Error21} Error
 */
Schemas.prototype['Error'] = undefined;






export default Schemas;

