/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Schema1 model module.
 * @module model/Schema1
 * @version 1.0.0
 */
class Schema1 {
    /**
     * Constructs a new <code>Schema1</code>.
     * @alias module:model/Schema1
     * @param ref {String} 
     */
    constructor(ref) { 
        
        Schema1.initialize(this, ref);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ref) { 
        obj['$ref'] = ref;
    }

    /**
     * Constructs a <code>Schema1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Schema1} obj Optional instance to populate.
     * @return {module:model/Schema1} The populated <code>Schema1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Schema1();

            if (data.hasOwnProperty('$ref')) {
                obj['$ref'] = ApiClient.convertToType(data['$ref'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} $ref
 */
Schema1.prototype['$ref'] = undefined;






export default Schema1;

