/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Script model module.
 * @module model/Script
 * @version 1.0.0
 */
class Script {
    /**
     * Constructs a new <code>Script</code>.
     * @alias module:model/Script
     * @param type {String} 
     * @param exec {String} 
     */
    constructor(type, exec) { 
        
        Script.initialize(this, type, exec);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, exec) { 
        obj['type'] = type;
        obj['exec'] = exec;
    }

    /**
     * Constructs a <code>Script</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Script} obj Optional instance to populate.
     * @return {module:model/Script} The populated <code>Script</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Script();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('exec')) {
                obj['exec'] = ApiClient.convertToType(data['exec'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
Script.prototype['type'] = undefined;

/**
 * @member {String} exec
 */
Script.prototype['exec'] = undefined;






export default Script;

