/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Assertions from './Assertions';
import Requests1 from './Requests1';

/**
 * The Stats1 model module.
 * @module model/Stats1
 * @version 1.0.0
 */
class Stats1 {
    /**
     * Constructs a new <code>Stats1</code>.
     * @alias module:model/Stats1
     * @param assertions {module:model/Assertions} 
     * @param requests {module:model/Requests1} 
     */
    constructor(assertions, requests) { 
        
        Stats1.initialize(this, assertions, requests);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assertions, requests) { 
        obj['assertions'] = assertions;
        obj['requests'] = requests;
    }

    /**
     * Constructs a <code>Stats1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Stats1} obj Optional instance to populate.
     * @return {module:model/Stats1} The populated <code>Stats1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Stats1();

            if (data.hasOwnProperty('assertions')) {
                obj['assertions'] = Assertions.constructFromObject(data['assertions']);
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = Requests1.constructFromObject(data['requests']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Assertions} assertions
 */
Stats1.prototype['assertions'] = undefined;

/**
 * @member {module:model/Requests1} requests
 */
Stats1.prototype['requests'] = undefined;






export default Stats1;

