/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Query1 from './Query1';
import Variable1 from './Variable1';

/**
 * The Url1 model module.
 * @module model/Url1
 * @version 1.0.0
 */
class Url1 {
    /**
     * Constructs a new <code>Url1</code>.
     * @alias module:model/Url1
     * @param raw {String} 
     * @param host {Array.<String>} 
     * @param path {Array.<String>} 
     */
    constructor(raw, host, path) { 
        
        Url1.initialize(this, raw, host, path);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, raw, host, path) { 
        obj['raw'] = raw;
        obj['host'] = host;
        obj['path'] = path;
    }

    /**
     * Constructs a <code>Url1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Url1} obj Optional instance to populate.
     * @return {module:model/Url1} The populated <code>Url1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Url1();

            if (data.hasOwnProperty('raw')) {
                obj['raw'] = ApiClient.convertToType(data['raw'], 'String');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], ['String']);
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], ['String']);
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], [Query1]);
            }
            if (data.hasOwnProperty('variable')) {
                obj['variable'] = ApiClient.convertToType(data['variable'], [Variable1]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} raw
 */
Url1.prototype['raw'] = undefined;

/**
 * @member {Array.<String>} host
 */
Url1.prototype['host'] = undefined;

/**
 * @member {Array.<String>} path
 */
Url1.prototype['path'] = undefined;

/**
 * @member {Array.<module:model/Query1>} query
 */
Url1.prototype['query'] = undefined;

/**
 * @member {Array.<module:model/Variable1>} variable
 */
Url1.prototype['variable'] = undefined;






export default Url1;

