/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The ValidResponse6 model module.
 * @module model/ValidResponse6
 * @version 1.0.0
 */
class ValidResponse6 {
    /**
     * Constructs a new <code>ValidResponse6</code>.
     * @alias module:model/ValidResponse6
     * @param user {module:model/User} 
     */
    constructor(user) { 
        
        ValidResponse6.initialize(this, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user) { 
        obj['user'] = user;
    }

    /**
     * Constructs a <code>ValidResponse6</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidResponse6} obj Optional instance to populate.
     * @return {module:model/ValidResponse6} The populated <code>ValidResponse6</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidResponse6();

            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/User} user
 */
ValidResponse6.prototype['user'] = undefined;






export default ValidResponse6;

