/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Environment1 from './Environment1';

/**
 * The ValidResponse3 model module.
 * @module model/ValidResponse3
 * @version 1.0.0
 */
class ValidResponse3 {
    /**
     * Constructs a new <code>ValidResponse3</code>.
     * @alias module:model/ValidResponse3
     * @param environment {module:model/Environment1} 
     */
    constructor(environment) { 
        
        ValidResponse3.initialize(this, environment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, environment) { 
        obj['environment'] = environment;
    }

    /**
     * Constructs a <code>ValidResponse3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidResponse3} obj Optional instance to populate.
     * @return {module:model/ValidResponse3} The populated <code>ValidResponse3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidResponse3();

            if (data.hasOwnProperty('environment')) {
                obj['environment'] = Environment1.constructFromObject(data['environment']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Environment1} environment
 */
ValidResponse3.prototype['environment'] = undefined;






export default ValidResponse3;

