/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Value model module.
 * @module model/Value
 * @version 1.0.0
 */
class Value {
    /**
     * Constructs a new <code>Value</code>.
     * @alias module:model/Value
     * @param key {String} 
     * @param value {String} 
     * @param type {String} 
     * @param enabled {Boolean} 
     * @param hovered {Boolean} 
     */
    constructor(key, value, type, enabled, hovered) { 
        
        Value.initialize(this, key, value, type, enabled, hovered);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, value, type, enabled, hovered) { 
        obj['key'] = key;
        obj['value'] = value;
        obj['type'] = type;
        obj['enabled'] = enabled;
        obj['hovered'] = hovered;
    }

    /**
     * Constructs a <code>Value</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Value} obj Optional instance to populate.
     * @return {module:model/Value} The populated <code>Value</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Value();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('hovered')) {
                obj['hovered'] = ApiClient.convertToType(data['hovered'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
Value.prototype['key'] = undefined;

/**
 * @member {String} value
 */
Value.prototype['value'] = undefined;

/**
 * @member {String} type
 */
Value.prototype['type'] = undefined;

/**
 * @member {Boolean} enabled
 */
Value.prototype['enabled'] = undefined;

/**
 * @member {Boolean} hovered
 */
Value.prototype['hovered'] = undefined;






export default Value;

