/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Variable2 model module.
 * @module model/Variable2
 * @version 1.0.0
 */
class Variable2 {
    /**
     * Constructs a new <code>Variable2</code>.
     * @alias module:model/Variable2
     * @param id {String} 
     * @param key {String} 
     * @param value {String} 
     * @param type {String} 
     */
    constructor(id, key, value, type) { 
        
        Variable2.initialize(this, id, key, value, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, key, value, type) { 
        obj['id'] = id;
        obj['key'] = key;
        obj['value'] = value;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Variable2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Variable2} obj Optional instance to populate.
     * @return {module:model/Variable2} The populated <code>Variable2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Variable2();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Variable2.prototype['id'] = undefined;

/**
 * @member {String} key
 */
Variable2.prototype['key'] = undefined;

/**
 * @member {String} value
 */
Variable2.prototype['value'] = undefined;

/**
 * @member {String} type
 */
Variable2.prototype['type'] = undefined;






export default Variable2;

