/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Version5 model module.
 * @module model/Version5
 * @version 1.0.0
 */
class Version5 {
    /**
     * Constructs a new <code>Version5</code>.
     * @alias module:model/Version5
     * @param id {String} 
     * @param name {String} 
     * @param api {String} 
     * @param schema {Array.<String>} 
     * @param createdBy {String} 
     * @param updatedBy {String} 
     * @param createdAt {String} 
     * @param updatedAt {String} 
     */
    constructor(id, name, api, schema, createdBy, updatedBy, createdAt, updatedAt) { 
        
        Version5.initialize(this, id, name, api, schema, createdBy, updatedBy, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, api, schema, createdBy, updatedBy, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['api'] = api;
        obj['schema'] = schema;
        obj['createdBy'] = createdBy;
        obj['updatedBy'] = updatedBy;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>Version5</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Version5} obj Optional instance to populate.
     * @return {module:model/Version5} The populated <code>Version5</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Version5();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('api')) {
                obj['api'] = ApiClient.convertToType(data['api'], 'String');
            }
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ApiClient.convertToType(data['schema'], ['String']);
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('updatedBy')) {
                obj['updatedBy'] = ApiClient.convertToType(data['updatedBy'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Version5.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Version5.prototype['name'] = undefined;

/**
 * @member {String} api
 */
Version5.prototype['api'] = undefined;

/**
 * @member {Array.<String>} schema
 */
Version5.prototype['schema'] = undefined;

/**
 * @member {String} createdBy
 */
Version5.prototype['createdBy'] = undefined;

/**
 * @member {String} updatedBy
 */
Version5.prototype['updatedBy'] = undefined;

/**
 * @member {String} createdAt
 */
Version5.prototype['createdAt'] = undefined;

/**
 * @member {String} updatedAt
 */
Version5.prototype['updatedAt'] = undefined;






export default Version5;

