/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VersionTag model module.
 * @module model/VersionTag
 * @version 1.0.0
 */
class VersionTag {
    /**
     * Constructs a new <code>VersionTag</code>.
     * @alias module:model/VersionTag
     * @param name {String} 
     * @param id {String} 
     */
    constructor(name, id) { 
        
        VersionTag.initialize(this, name, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, id) { 
        obj['name'] = name;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>VersionTag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VersionTag} obj Optional instance to populate.
     * @return {module:model/VersionTag} The populated <code>VersionTag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionTag();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
VersionTag.prototype['name'] = undefined;

/**
 * @member {String} id
 */
VersionTag.prototype['id'] = undefined;






export default VersionTag;

