/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Version1 model module.
 * @module model/Version1
 * @version 1.0.0
 */
class Version1 {
    /**
     * Constructs a new <code>Version1</code>.
     * @alias module:model/Version1
     * @param id {String} 
     * @param name {String} 
     * @param api {String} 
     */
    constructor(id, name, api) { 
        
        Version1.initialize(this, id, name, api);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, api) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['api'] = api;
    }

    /**
     * Constructs a <code>Version1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Version1} obj Optional instance to populate.
     * @return {module:model/Version1} The populated <code>Version1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Version1();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('api')) {
                obj['api'] = ApiClient.convertToType(data['api'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Version1.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Version1.prototype['name'] = undefined;

/**
 * @member {String} api
 */
Version1.prototype['api'] = undefined;






export default Version1;

