/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Version4 model module.
 * @module model/Version4
 * @version 1.0.0
 */
class Version4 {
    /**
     * Constructs a new <code>Version4</code>.
     * @alias module:model/Version4
     * @param id {String} 
     */
    constructor(id) { 
        
        Version4.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Version4</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Version4} obj Optional instance to populate.
     * @return {module:model/Version4} The populated <code>Version4</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Version4();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Version4.prototype['id'] = undefined;






export default Version4;

