/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Version6 model module.
 * @module model/Version6
 * @version 1.0.0
 */
class Version6 {
    /**
     * Constructs a new <code>Version6</code>.
     * @alias module:model/Version6
     * @param id {String} 
     * @param name {String} 
     * @param summary {String} 
     * @param description {String} 
     * @param createdBy {String} 
     * @param createdAt {String} 
     * @param updatedAt {String} 
     */
    constructor(id, name, summary, description, createdBy, createdAt, updatedAt) { 
        
        Version6.initialize(this, id, name, summary, description, createdBy, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, summary, description, createdBy, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['summary'] = summary;
        obj['description'] = description;
        obj['createdBy'] = createdBy;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>Version6</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Version6} obj Optional instance to populate.
     * @return {module:model/Version6} The populated <code>Version6</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Version6();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Version6.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Version6.prototype['name'] = undefined;

/**
 * @member {String} summary
 */
Version6.prototype['summary'] = undefined;

/**
 * @member {String} description
 */
Version6.prototype['description'] = undefined;

/**
 * @member {String} createdBy
 */
Version6.prototype['createdBy'] = undefined;

/**
 * @member {String} createdAt
 */
Version6.prototype['createdAt'] = undefined;

/**
 * @member {String} updatedAt
 */
Version6.prototype['updatedAt'] = undefined;






export default Version6;

