/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Version3 model module.
 * @module model/Version3
 * @version 1.0.0
 */
class Version3 {
    /**
     * Constructs a new <code>Version3</code>.
     * @alias module:model/Version3
     * @param id {String} 
     * @param name {String} 
     * @param createdAt {String} 
     * @param updatedAt {String} 
     * @param api {String} 
     * @param createdBy {String} 
     * @param updatedBy {String} 
     */
    constructor(id, name, createdAt, updatedAt, api, createdBy, updatedBy) { 
        
        Version3.initialize(this, id, name, createdAt, updatedAt, api, createdBy, updatedBy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, createdAt, updatedAt, api, createdBy, updatedBy) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
        obj['api'] = api;
        obj['createdBy'] = createdBy;
        obj['updatedBy'] = updatedBy;
    }

    /**
     * Constructs a <code>Version3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Version3} obj Optional instance to populate.
     * @return {module:model/Version3} The populated <code>Version3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Version3();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('api')) {
                obj['api'] = ApiClient.convertToType(data['api'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('updatedBy')) {
                obj['updatedBy'] = ApiClient.convertToType(data['updatedBy'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Version3.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Version3.prototype['name'] = undefined;

/**
 * @member {String} createdAt
 */
Version3.prototype['createdAt'] = undefined;

/**
 * @member {String} updatedAt
 */
Version3.prototype['updatedAt'] = undefined;

/**
 * @member {String} api
 */
Version3.prototype['api'] = undefined;

/**
 * @member {String} createdBy
 */
Version3.prototype['createdBy'] = undefined;

/**
 * @member {String} updatedBy
 */
Version3.prototype['updatedBy'] = undefined;






export default Version3;

