/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PostmanApi);
  }
}(this, function(expect, PostmanApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PostmanApi.Response1();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Response1', function() {
    it('should create an instance of Response1', function() {
      // uncomment below and update the code to test Response1
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be.a(PostmanApi.Response1);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property originalRequest (base name: "originalRequest")', function() {
      // uncomment below and update the code to test the property originalRequest
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property postmanPreviewlanguage (base name: "_postman_previewlanguage")', function() {
      // uncomment below and update the code to test the property postmanPreviewlanguage
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property header (base name: "header")', function() {
      // uncomment below and update the code to test the property header
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property cookie (base name: "cookie")', function() {
      // uncomment below and update the code to test the property cookie
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property responseTime (base name: "responseTime")', function() {
      // uncomment below and update the code to test the property responseTime
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instane = new PostmanApi.Response1();
      //expect(instance).to.be();
    });

  });

}));
