/**
 * Postman API
 * Postman API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PostmanApi);
  }
}(this, function(expect, PostmanApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PostmanApi.APIVersionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('APIVersionApi', function() {
    describe('createAPIVersion', function() {
      it('should call createAPIVersion successfully', function(done) {
        //uncomment below and update the code to test createAPIVersion
        //instance.createAPIVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteanAPIVersion', function() {
      it('should call deleteanAPIVersion successfully', function(done) {
        //uncomment below and update the code to test deleteanAPIVersion
        //instance.deleteanAPIVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllAPIVersions', function() {
      it('should call getAllAPIVersions successfully', function(done) {
        //uncomment below and update the code to test getAllAPIVersions
        //instance.getAllAPIVersions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getanAPIVersion', function() {
      it('should call getanAPIVersion successfully', function(done) {
        //uncomment below and update the code to test getanAPIVersion
        //instance.getanAPIVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateanAPIVersion', function() {
      it('should call updateanAPIVersion successfully', function(done) {
        //uncomment below and update the code to test updateanAPIVersion
        //instance.updateanAPIVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
